---
# tasks file for docker

- apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg 
    state: present

- apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes

- apt:
    name: docker-ce
    state: present

- name: Create group docker if not there
  group:
    name: docker
    state: present

- name: Add server user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

